### PR TITLE
fix: check recording finished in request hook

### LINKED ISSUE #52: `AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value: (0, node_assert_1.default)(this.stream)`
To reproduce, run the following command in `packages/client` in `appmap-js`:
```
npx appmap-node@latest yarn jest appMap.create.spec.ts
```
I get the following output:
```
(Λ) Running with appmap-node version 2.6.1
(Λ) Detected Jest. Tests will be automatically recorded.
(Λ) Wrote 5 AppMaps to /home/ahtrotta/projects/appmap/appmap-js/packages/client/tmp/appmap/jest/appMap/

 RUNS  test/appMap.create.spec.ts
node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, node_assert_1.default)(this.stream)

    at Recording.httpClientRequest (/home/ahtrotta/.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/Recording.ts:80:11)
    at OverriddenClientRequest.<anonymous> (/home/ahtrotta/.npm/_npx/a04c6870cebb0c63/node_modules/appmap-node/src/hooks/http.ts:69:42)
    at OverriddenClientRequest.emit (node:events:513:28)
    at InterceptedRequestRouter.startPlayback (/home/ahtrotta/projects/appmap/appmap-js/node_modules/nock/lib/intercepted_request_router.js:310:11)
    at InterceptedRequestRouter.maybeStartPlayback (/home/ahtrotta/projects/appmap/appmap-js/node_modules/nock/lib/intercepted_request_router.js:262:12)
    at InterceptedRequestRouter.connectSocket (/home/ahtrotta/projects/appmap/appmap-js/node_modules/nock/lib/intercepted_request_router.js:140:12)
    at /home/ahtrotta/projects/appmap/appmap-js/node_modules/nock/lib/intercepted_request_router.js:78:33
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

Node.js v18.16.0
```

### PR DESCRIPTION
**Pull request by zermelo-wisen**
Fixes #52

### CODE REVIEW

File: src/hooks/http.ts [hunk 1]
```diff
@@ -64,6 +64,9 @@ function handleClientRequest(request: http.ClientRequest) {
 
   const startTime = getTime();
   request.on("finish", () => {
+    // recording may have finished at this point
+    if (!recording.running) return;
```
Comment (dividedmind) [inline src/hooks/http.ts:68]: We should probably show a warning here — this might point to a problem with the instrumented test.

File: test/httpClient/test.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
+const http = require("node:http");
+const nock = require("nock");
+
+function mock() {
+  nock("http://localhost:3000").get("/").twice().reply(200);
+  // request "finished" callback will be registered inside httpHook
+  // but it (callback) won't be called before the test finishes.
+  http.get("http://localhost:3000/");
```
Comment (dividedmind) [inline test/httpClient/test.js:8]: I wonder, why doesn't this request show up in the AppMap?

File: test/httpClient/package.json [hunk 3]
```diff
@@ -3,6 +3,7 @@
   "packageManager": "yarn@3.6.3",
   "private": true,
   "dependencies": {
+    "jest": "^29.7.0",
```
Comment (dividedmind) [inline test/httpClient/package.json:6]: This should use the same jest version as the other packages, to avoid pulling multiple versions in dependencies.

**Review by dividedmind — CHANGES_REQUESTED** [review]

**Review by dividedmind — APPROVED** [review]
