### PR TITLE
fix: Add '--loader ts-node/esm' node options if esm: true in tsconfig

### LINKED ISSUE #63: Node agent fails with "Error transforming source"
While trying to map [this repo](https://github.com/Authress/express-starter-kit): 

```
*[main][~/code/express-starter-kit]$ npx appmap-node npm start 
(Λ) Running with appmap-node version 2.7.0

> express-starter-kit@1.0.0 start
> nodemon src/index.ts

[nodemon] 2.0.21
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,js,json
[nodemon] starting `node --loader ts-node/esm src/index.ts`
(Λ) Error transforming source at file:///Users/brikelly/code/express-starter-kit/src/boilerplate.ts: [17:12]: Expected ')'
(Λ) Error transforming source at file:///Users/brikelly/code/express-starter-kit/src/authressTokenValidation.ts: [6:10]: Expected ')'
(Λ) Error transforming source at file:///Users/brikelly/code/express-starter-kit/src/accounts/accountController.ts: [12:31]: Expected ')'
(Λ) Error transforming source at file:///Users/brikelly/code/express-starter-kit/src/users/usersController.ts: [12:46]: Expected ')'
(Λ) Error transforming source at file:///Users/brikelly/code/express-starter-kit/src/resourceManagement/exampleResourceController.ts: [12:53]: Expected ')'
(Λ) Error transforming source at file:///Users/brikelly/code/express-starter-kit/src/accounts/accountsRepository.ts: [3:29]: Expected ')'
(Λ) Error transforming source at file:///Users/brikelly/code/express-starter-kit/src/authressPermissionsWrapper.ts: [20:30]: Expected ')'
(Λ) Error transforming source at file:///Users/brikelly/code/express-starter-kit/src/resourceManagement/exampleDataRepository.ts: [3:25]: Expected ')'
App Running on http://localhost:8080/```

### PR DESCRIPTION
**Pull request by zermelo-wisen**
Fixes #63

### CODE REVIEW

File: src/bin.ts [hunk 1]
```diff
@@ -50,8 +50,8 @@ export function main() {
 }
 
 function isTsEsmLoaderNeeded(cmd: string, args: string[]) {
-  // HACK: Ugly way to check if it's ts-node instead of node
-  return [cmd, ...args].includes("ts-node");
+  // HACK: Ugly way to check
+  return [cmd, ...args].includes("ts-node") || existsSync(join(cwd(), "tsconfig.json"));
```
Comment (dividedmind) [inline src/bin.ts:54]: I don't think this is a good idea. The presence of `tsconfig` doesn't mean `ts-node` is available or the project uses it.

**Review by dividedmind — CHANGES_REQUESTED** [review]

File: src/bin.ts [hunk 2]
```diff
@@ -50,8 +52,20 @@ export function main() {
 }
 
 function isTsEsmLoaderNeeded(cmd: string, args: string[]) {
-  // HACK: Ugly way to check if it's ts-node instead of node
-  return [cmd, ...args].includes("ts-node");
+  // HACK: Ugly way to check
+  const tsConfigTsNodeEsmIsTrue = () => {
+    const tsConfigPath = join(cwd(), "tsconfig.json");
```
Comment (dividedmind) [inline src/bin.ts:57]: Should use `config.root` instead of `cwd()`. Also, it should search up — tsconfig could be in an ancestor directory.

File: src/bin.ts [hunk 3]
```diff
@@ -50,8 +52,20 @@ export function main() {
...
+    if (!existsSync(tsConfigPath)) return false;
+
+    const tsConfigContent = readFileSync(tsConfigPath, "utf-8");
+    const tsConfig = parseConfigFileTextToJson("", tsConfigContent).config as {
```
Comment (dividedmind) [inline src/bin.ts:61]: Why not use `readJsonConfigFile` directly?

File: src/bin.ts [hunk 4]
```diff
@@ -50,8 +52,20 @@ export function main() {
...
+      "ts-node"?: { esm?: boolean };
```
Comment (dividedmind) [inline src/bin.ts:62]: This will cause an error when `tsconfig.json` is malformed. You should cast it to `unknown` and check the types explicitly instead.

**Review by dividedmind — CHANGES_REQUESTED** [review]
Please add an integration test that would have failed before but now passes.

**Review by dividedmind — CHANGES_REQUESTED** [review]
Integration test still missing.

**Review by dividedmind — APPROVED** [review]
