### PR TITLE
fix: Prisma recordings on extended Prisma clients

### LINKED ISSUE #127: SQL with Prisma client are not being recorded by AppMap
Using the latest release of [Cal.com](https://github.com/calcom/cal.com)

Using `appmap-node` version `2.18.0`

Using the default appmap.yml

```
name: calcom-monorepo
appmap_dir: tmp/appmap
packages:
  - path: .
    exclude:
      - node_modules
      - .yarn
```

When interacting with the application to create AppMaps with DB queries we are unable to see the SQL and instead the DB interactions are represented within the AppMap strangely.

Screenshot 2024-03-15 at 1 29 54 PM

[Further replicated in this Loom video](https://www.loom.com/share/6906d8fda0dd434d8f2f4e86103a3133)

### PR DESCRIPTION
**Pull request by zermelo-wisen**
Fixes #127 

We do two types of Prisma recordings:
1. SQL queries sent to the db as appmap sql query events.
2. Prisma Client Queries (create, findUnique, findMany, ...) as appmap funcion call events.

This fixes two problems reported in #127, that seem to occur with extended Prisma clients.
1. SQLs not recorded.
2. Repeated Prisma Client Queries.

### CODE REVIEW

File: src/hooks/prisma.ts [hunk 1]
```diff
@@ -10,15 +10,39 @@ import { FunctionInfo } from "../registry";
...
+  // (2) SQL Queries: We have to change config parameters (logLevel, logQueries)
+  // and register a prismaClient.$on("query") handler to record sql queries.
+  // We have to do it by proxying mod.PrismaClient here, since it turned out that
+  // it's too late to do it inside the first invocation of the _request method,
+  // because $on is (becomes?) undefined in extended prisma clients.
+  // https://www.prisma.io/docs/orm/reference/prisma-client-reference#remarks-37
+
+  // Normally, we "Cannot assign to 'PrismaClient' because it is a read-only property."
+  // Fortunately with this hack it can be done.
+  const modHacked = mod as unknown as { PrismaClient: unknown };
```
Comment (dividedmind) [inline src/hooks/prisma.ts:25]: Maybe we could use `Object.defineProperty()` instead?

File: src/hooks/prisma.ts [hunk 2]
```diff
@@ -10,15 +10,39 @@ import { FunctionInfo } from "../registry";
...
+  modHacked.PrismaClient = new Proxy(mod.PrismaClient, {
+    construct(target, argArray, newTarget): object {
+      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-argument
+      const result = Reflect.construct(target, argArray, newTarget);
+      if (!hookAttached) {
+        hookAttached = true;
```
Comment (dividedmind) [inline src/hooks/prisma.ts:31]: I didn't notice it before, but now I can see `hookAttached` is a global. I know it's an edge case, but it will break if there are multiple prisma clients (as can be configured with multiple `prisma:` entries in the config file). How about using a `WeakSet` instead to keep track of patched clients?

File: src/hooks/prisma.ts [hunk 3]
```diff
@@ -59,9 +83,7 @@ function getFunctionInfo(model: string, action: string, moduleId: string) {
   const key = model + "." + action;
 
   if (!functionInfos.has(key)) {
-    const params = ["data", "include", "where"].map((k) => {
-      return { type: "Identifier", name: k } as ESTree.Identifier;
-    });
+    const params = [{ type: "Identifier", name: "args" } as ESTree.Identifier];
```
Comment (dividedmind) [inline src/hooks/prisma.ts:86]: Not sure why this change is necessary. Nb, you can use `generate.identifier()`.

File: src/hooks/prisma.ts [hunk 4]
```diff
@@ -77,50 +99,21 @@ function getFunctionInfo(model: string, action: string, moduleId: string) {
...
       let prismaCall: AppMap.FunctionCallEvent | undefined;
       if (argArray?.length > 0) {
         const requestParams = argArray[0] as PrismaRequestParams;
-
         if (requestParams.action && requestParams.model) {
           prismaCall = recording.functionCall(
             getFunctionInfo(requestParams.model, requestParams.action, moduleId),
             requestParams.model,
-            [requestParams.args?.data, requestParams.args?.include, requestParams.args?.where],
+            [requestParams.args?.data, requestParams.args?.include, requestParams?.args?.where],
```
Comment (dividedmind) [inline src/hooks/prisma.ts]: Why only `?` in one case? Surely either all can be undefined or none.

File: test/__snapshots__/prisma.test.ts.snap [hunk 5]
```diff
@@ -392,50 +363,13 @@ exports[`mapping Prisma tests 1`] = `
...
-          "name": "include",
-          "value": "undefined",
-        },
-        {
-          "class": "undefined",
-          "name": "where",
-          "value": "undefined",
+          "class": "String",
+          "name": "args",
+          "value": "'{"data":{"name":"Alice","email":"alice@prisma.io"}}'",
```
Comment (dividedmind) [inline test/__snapshots__/prisma.test.ts.snap:372]: Why is this recorded as a string? Should probably be an object.

File: src/hooks/prisma.ts [hunk 6]
```diff
@@ -110,11 +117,32 @@ function createPrismaClientMethodProxy<T extends (...args: unknown[]) => unknown
       if (argArray?.length > 0) {
         const requestParams = argArray[0] as PrismaRequestParams;
         if (requestParams.action && requestParams.model) {
-          prismaCall = recording.functionCall(
-            getFunctionInfo(requestParams.model, requestParams.action, moduleId),
-            requestParams.model,
-            [requestParams.args?.data, requestParams.args?.include, requestParams?.args?.where],
-          );
+          // In extended prisma clients, we receive repeated calls
+          // with the same action, module and args. It can be seen
```
Comment (dividedmind) [inline src/hooks/prisma.ts:121]: I suspect the problem might be that we're patching the same client multiple times. You can double check by looking at `this`, `this.prototype` and the proxy; if I'm right, the calls will have the same `this` and `prototype` but different proxies. In this case, perhaps you can track the created proxies using a `WeakSet` to ensure you're not repatching.

**Review by dividedmind — CHANGES_REQUESTED** [review]

File: src/hooks/prisma.ts (hunk 3 above)
Comment (zermelo-wisen) [reply src/hooks/prisma.ts:86]: There can be lots of options like `data, select, include, where, orderBy, take, skip, distinct, cursor, relationLoadStrategy,` etc. Having a parameter for each one seeme not to look good when exploring the AppMap in the viewer, since most of them are irrelevant in a specific call and end up showing as "undefined." 

Making different subsets of parameters for each Prisma model query isn't practical either, because, for example, `findMany` can have around 10 options and many or them will again be "undefined" in a specific call.

Comment (dividedmind) [reply src/hooks/prisma.ts:86]: Makes sense, thanks.

**Review by dividedmind — APPROVED** [review]
