### PR TITLE
fix: Handle parent Ctrl-C in child process

### LINKED ISSUE #118: Process recording doesn't complete
Running AppMap index service:

```
npx appmap-node env APPLAND_API_KEY=<key> node ./built/cli.js index -d ~/source/appland/appland -v -w -p 30101 
```

When the process is terminated via Ctrl-C, the `part` file is left behind and not completed as an appmap.json.

Branch you can use: https://github.com/getappmap/appmap-js/pull/1603

You can trigger a request to the service like this:

```
node ./bin/rpcClient explain '{"question":"Add a captcha to the user login" }'
```

Or

```
./bin/rpcClient search '{"query":"maxresults up-to-date parameters settings config maximumresults limit current updated latest","maxResults":10}'
```

Use your imagination :-)

### PR DESCRIPTION
**Pull request by zermelo-wisen**
Fixes #118

### CODE REVIEW

File: src/util/forwardSignals.ts [hunk 1]
```diff
@@ -5,7 +5,12 @@ export default function forwardSignals(
   signals = DEFAULT_FORWARD,
 ) {
   const forward = proc.kill.bind(proc);
-  for (const signal of signals) process.on(signal, forward);
+  // Without setTimeout, child does not handle forwarded SIGINT
+  // caused by the parent receiving a Ctrl-C in certain cases.
+  // See: simple.test.ts "forwards SIGINT (ctrl-c) properly
+  // to the grandchild having active setInterval"
+  for (const signal of signals)
+    process.on(signal, (...args) => setTimeout(() => forward(...args), 100));
```
Comment (dividedmind) [inline src/util/forwardSignals.ts:13]: Will `setImmediate` work here instead?

File: test/simple.test.ts [hunk 2]
```diff
@@ -43,6 +46,47 @@ integrationTestSkipOnWindows("forwarding signals to the child", async () => {
...
+    // not finish and we are not able to get the SIGINT in
+    // appmap-node process.
+    // https://krasimirtsonev.com/blog/article/Nodejs-managing-child-processes-starting-stopping-exec-spawn#killing-stopping-the-command
+    psTree(child.pid!, function (err, children) {
+      children.forEach((child) => process.kill(parseInt(child.PID), "SIGINT"));
+    });
+
+    await new Promise<void>((r) => {
+      const handler = (): void => {
+        child.removeListener("exit", handler);
```
Comment (dividedmind) [inline test/simple.test.ts:80]: `removeListener` shouldn't be needed with `once` — you should be able to just do `child.once('exit', r)`.

File: test/simple.test.ts [hunk 3]
```diff
@@ -43,6 +46,47 @@ integrationTestSkipOnWindows("forwarding signals to the child", async () => {
...
+    child.kill("SIGINT");
+
+    // child.kill does not kill all grandchildren, we have to
+    // send the kill signal to all of them. Otherwise Jest will
+    // not finish and we are not able to get the SIGINT in
+    // appmap-node process.
+    // https://krasimirtsonev.com/blog/article/Nodejs-managing-child-processes-starting-stopping-exec-spawn#killing-stopping-the-command
+    psTree(child.pid!, function (err, children) {
+      children.forEach((child) => process.kill(parseInt(child.PID), "SIGINT"));
+    });
```
Comment (dividedmind) [inline test/simple.test.ts:76]: Isn't the whole point of the fix to make this unnecessary?

File: test/simple.test.ts [hunk 4]
```diff
@@ -43,6 +46,47 @@ integrationTestSkipOnWindows("forwarding signals to the child", async () => {
...
 
+integrationTestSkipOnWindows(
+  "forwards SIGINT (ctrl-c) properly to the grandchild having active setInterval",
+  async () => {
+    // This test tests a fix (see: forwardSignals.ts) for a bug which occured
+    // when there is a script with active setInterval call and appmap-node
+    // runs this script indirectly with a node process: appmap-node node interval.js.
+    // We run the commands similarly as reported in:
+    // https://github.com/getappmap/appmap-node/issues/118
+    const child = spawn("npx", [getAppMapBinPath(), "node", "interval.js"], {
```
Comment (dividedmind) [inline test/simple.test.ts:57]: Why `npx` instead of `node`?

File: src/util/forwardSignals.ts (hunk 1 above)
Comment (zermelo-wisen) [reply src/util/forwardSignals.ts:13]: I tested it, unfortunately, neither `setImmediate` nor `process.nextTick` helps.

File: test/simple.test.ts (hunk 3 above)
Comment (zermelo-wisen) [reply test/simple.test.ts:76]: Actually, I had to do this just to be able to kill all the process hierarchy after spawning `npx appmap-node node interval.js` inside a Jest test. It seems, here in Jest, sending SIGINT to the spawned process (shell in this case) does not seem to propagate to all the hierarchy.

File: test/simple.test.ts (hunk 4 above)
Comment (zermelo-wisen) [reply test/simple.test.ts:57]: I was able to consistently create same buggy behavior only with `npx` in `Jest`. Considering that original command reported in the issue was using `npx`, I believe it represents the core problem.

Substituting `node` for `npx` in the test does not fail but I've also manually tested it with `node`, as you suggested in the issue: It fails without the fix and succeeds with the fix.

On the other hand, since the issue revolves around properly handling signals (Ctrl-C in this case) across multiple processes, I'm uncertain whether it's possible to simulate exact same circumstances of receiving Ctrl-C in [`npx` -> `node appmap-node` -> `node intervalScript.js`] vs. [`Jest Runner` -> `shell` -> `npx` -> `node appmap-node` -> `node intervalScript.js`]. This configuration was the closest I could set up in a `Jest` test.

**Review by dividedmind — CHANGES_REQUESTED** [review]
I'm not sure what's going on here, but the test still passes even after I revert the change.

**Comment by dividedmind** [comment]
Ok, I know what's going on. Ctrl-C on a terminal sends SIGINT to the whole process group; this causes a race in the child which gets the signal, removes the handler, then gets another SIGINT immediately, forwarded from appmap-node; with the handler now missing, node dies instantly.

**Comment by zermelo-wisen** [comment]
To better understand the situation with the current fix...

Here is the fix controlled with the env variable (FIX) for testing purposes temporarily.

image


✅ 
image

❌
image

✅
image

With npx instead of node
image

**Comment by dividedmind** [comment]
Note to self: make sure `APPMAP_RECORDER_PROCESS_ALWAYS=true npx appmap-node node ./built/cli.js rpc -p 30108 -d ~/source/appland/appmap-js --log-navie` still works as expected.

**Review by dividedmind — APPROVED** [review]
