### PR TITLE
fix: Double sql recording in PostgreSQL

### LINKED ISSUE #64: SQL queries appear to be double-counted
While mapping [this repo](https://github.com/bunnyapp/sample-saas), we noticed that all SQL queries happen at least twice (or as multiples of 2). It's likely that SQL queries are getting double-counted.

Image

### PR DESCRIPTION
**Pull request by zermelo-wisen**
Fixes #64.

Removed proxying Pool.query method because it uses Client.query internally.

### CODE REVIEW

File: test/postgres/index.js [hunk 1]
```diff
@@ -5,11 +5,13 @@ function main() {
...
+  // We can't record Pool.query without a real database because it uses
+  // Client.query internally and it will throw before calling it in this case.
 
   new pg.Client().query("select * from customer where id = 1001").catch(() => {
     /* empty */
   });
-  new pg.Pool().query("select * from invoice where customer_id = 1001").catch(() => {
+  new pg.Client().query("select * from invoice where customer_id = 1001").catch(() => {
     /* empty */
   });
```
Comment (dividedmind) [inline test/postgres/index.js:16]: You can just remove this.

**Review by dividedmind — APPROVED** [review]
