### PR TITLE
fix: Request recording abandons test recording

### LINKED ISSUE #132: Integration tests in appmap-js/packages/cli don't generate AppMaps
Checkout and build appmap-js.

Go to `packages/cli`. Run `npx appmap-node jest tests/integration`. Output folders are generated, but no AppMaps are created.

### PR DESCRIPTION
**Pull request by zermelo-wisen**
Fixes #132

### CODE REVIEW

File: src/recorder.ts [hunk 1]
```diff
@@ -93,23 +127,69 @@ function isNullPrototype(obj: unknown) {
...
+}
+
+export function startProcessRecording() {
+  if (!processRecordingShouldAlwaysBeActive) assert(!processRecording?.running);
+  if (!processRecording?.running)
+    processRecording = new Recording("process", "process", new Date().toISOString());
+}
+
+export function startTestRecording(
+  type: AppMap.RecorderType,
```
Comment (dividedmind) [inline src/recorder.ts:141]: Isn't this always supposed to be `tests`?

**Review by dividedmind — APPROVED** [review]
Good work! Sorry it took so long to review.
